# This is a basic workflow to trigger packer buil on merge commit into main branch


name: Run packer build on commit merge and maually using workflow dispatch
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: packer validate ami.json
      - run: packer build ami.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_PROD_ID: ${{ secrets.AWS_PROD_ID }}
          AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
